version: '3.8'

services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
      - "5173:5173"  # Vite dev server port
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DATABASE_URL=file:/app/data/db.sqlite
    volumes:
      - .:/app
      - /app/node_modules
      - app_data_dev:/app/data
      - ./uploads:/app/uploads
    restart: unless-stopped
    command: npm run dev

volumes:
  app_data_dev:
    driver: local